server:
  port: 5233
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./clean-architecture-h2-db
    username: sa
    password: password
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
